services:
  slurmjupyter:
        image: slurm-jupyter:latest
        hostname: slurmjupyter
        user: admin
        volumes:
                - ./shared:/home/admin/shared
        ports:
                - 8888:8888 # jupyterlab
        networks:
                - slurmnet
        depends_on:
                - slurmmaster
  slurmmaster:
        image: slurm-master:latest
        hostname: slurmmaster
        user: admin
        volumes:
                - ./shared:/home/admin/shared
        networks:
                - slurmnet
  slurmnode1: &slurmnode1
        image: slurm-node:latest
        hostname: slurmnode1
        user: admin
        volumes:
                - ./shared:/home/admin/shared
        networks:
                - slurmnet
        depends_on:
                - slurmmaster
  slurmnode2:
        <<: *slurmnode1
        hostname: slurmnode2
  slurmnode3:
        <<: *slurmnode1
        hostname: slurmnode3

networks:
  slurmnet:
