.PHONY: clean

clean:
	# We use "-f" as intended to do the clean up from outside the docker container and files created from inside the docker container might not be created rwx for all by default
	-rm -f *.out
